// Swap action type names
export const SET_POOL = 'SET_POOL';
export const SET_FOCUS = 'SET_FOCUS';
export const SET_TOKEN1 = 'SET_TOKEN1';
export const SET_TOKEN2 = 'SET_TOKEN2';
export const SET_SETTINGS = 'SET_SETTINGS';
export const SWITCH_TOKENS = 'SWITCH_TOKENS';
export const SET_TOKEN1_AMOUNT = 'SET_TOKEN1_AMOUNT';
export const SET_TOKEN2_AMOUNT = 'SET_TOKEN2_AMOUNT';
export const SET_TOKEN_PRICES = 'SET_TOKEN_PRICES';
export const CLEAR_TOKEN_AMOUNTS = 'CLEAR_TOKEN_AMOUNTS';
export const SET_STATUS = 'SET_STATUS';
export const SET_COMPLETE_STATUS = 'SET_COMPLETE_STATUS';
export const SET_LOADING = 'SET_LOADING';
export const SET_VALIDITY = 'SET_VALIDITY';
export const SET_NEW_POOL_SUPPLY = 'SET_NEW_POOL_SUPPLY';
export const SET_PERCENTAGE = 'SET_PERCENTAGE';
